[package]
name = "upbit"
version = "1.3.1"
edition = "2021"
description = "rust_upbit_api with upbit api version v1.3.4"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
hmac = "0.12.1"
jsonwebtokens = "1.1.0"
serde_json = "1.0.87"
sha2 = "0.10.6"
uuid = { version = "1.2.1", features = ["v4", "serde"] }
serde = "1.0.147"
serde_with = { version = "2.0.1", features = ["json"] }
envmnt = "0.10.4"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
